### PR TITLE
ARM: Fixed mmap() security issue

### LINKED ISSUE #6: Insecure memory access permission to .text section in ARM
In lib-support.h 
```
asm(".pushsection .text,\"ax\", \"progbits\""    "\n" \
        "slowpath_common:"                              "\n" \
        PUSH(plt_handle, REG_IP)                   "\n" \
```
after expanding PUSH() in ARM
```
ldr r3, =plt_handle  
ldr r2, [r3] 
push {r2}
```
and `ldr r3, =plt_handle` will be assembled as 
```
2ec: e59f3070  ldr r3, [pc, #112]  ; 364 <test_import1+0x18>
364: 00011034  .word 0x00011034
```
The problem is:
**`364: 00011034  .word 0x00011034` will appear in .rel.dyn that we must relocate the offset of 364.
**BUT the offset of 364 locates in .text.****
So we have to give WRITE permission to make .text relocatable during `mmap()`.

.text section must have only READ and EXECUTE permission.

### PR DESCRIPTION
**Pull request by lecopzer**
Resolve #6 
Assuming first PT_LOAD without PF_W is always the code section.
The `addr` in code section is given WRITE permission temporarily
when relocating its address.

(
In ARM document:

Although the fromelf output shows ER_RO starting at address 0x8000, it
can be relocated or loaded to a different address such as 0x9000 by the
dynamic linker.

Ref:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0242a/BCGHDBCB.html
)

### CODE REVIEW

**Review by jserv — COMMENTED** [review]
Improve Git commit messages. The body should be written in plain and valid English. Reference would be listed in the end.

File: loader.c [hunk 1]
```diff
@@ -309,7 +308,16 @@ dloader_p api_load(const char *filename)
         case R_ARM_RELATIVE:
         {
             ElfW(Addr) *addr = (ElfW(Addr) *)(load_bias + reloc->r_offset);
-            *addr += load_bias;
+            if ((intptr_t) addr < ro_end && (intptr_t) addr >= ro_start)
```
Comment (jserv) [inline loader.c]: Use `clang-format -i` to reformat.

File: loader.c [hunk 2]
```diff
@@ -309,7 +308,16 @@ dloader_p api_load(const char *filename)
...
+            {
+                mprotect((void*) round_down((intptr_t) addr, pagesize),
+                         pagesize, PROT_WRITE);
+                *addr += load_bias;
```
Comment (jserv) [inline loader.c]: The code is a bit tricky. Would it be working with Aarch64 as well?

Comment (lecopzer) [reply loader.c]: I've tried a build pass version with Aarch64.
Its also shows same things in .rela.dyn
```
Relocation section '.rela.dyn' at offset 0x328 contains 12 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
0000000004d0  000000000403 R_AARCH64_RELATIV                    11048
0000000004d8  000000000403 R_AARCH64_RELATIV                    11050
0000000004e0  000000000403 R_AARCH64_RELATIV                    11040
```

Comment (lecopzer) [reply loader.c]: I need to do a full porting to Aarch64 to confirm the answer.

File: loader.c [hunk 3]
```diff
@@ -309,7 +308,15 @@ dloader_p api_load(const char *filename)
         case R_ARM_RELATIVE:
         {
             ElfW(Addr) *addr = (ElfW(Addr) *)(load_bias + reloc->r_offset);
-            *addr += load_bias;
+            if ((intptr_t) addr < ro_end && (intptr_t) addr >= ro_start) {
```
Comment (jserv) [inline loader.c]: The code looks tricky to me. Please add comments around.

Comment (lecopzer) [reply loader.c]: Done. Review please.

File: loader.c [hunk 4]
```diff
@@ -298,6 +294,9 @@ dloader_p api_load(const char *filename)
     }
     assert(dynamic != NULL);
 
+    ElfW(Addr) ro_start = ro_load->p_offset + load_bias;
+    ElfW(Addr) ro_end = ro_load->p_offset + load_bias +
```
Comment (jserv) [inline loader.c]: Rewriting as `ElfW(Addr) ro_end = ro_start + ro_load->p_memsz;` would look better.

**Review by jserv — COMMENTED** [review]
Add "Close #6" to let GitHub close related issue automatically.

Reference: https://help.github.com/articles/closing-issues-using-keywords/

File: loader.c (hunk 4 above)
Comment (lecopzer) [reply loader.c]: Done.
